### Participantes
- Leidy Jaramillo Parra
- Lucero Zarate Herrera
- Víctor Echavarría Hernandez


# **Prueba \#1**

En la siguiente pureba se evalua de manera EXCLUSIVA lo que se solicita, cualquier otra respuesta adicional a ella será valorada, más no evaluada. Entregue la prueba en un repositorio de github antes de el lunes 7 de agosto a las 06:59:59.



## **Ejercicio 1** (50 pts)

Escriba una clase `Pedido` que pueda ser usada para gestionar la información de los pedidos realizados a una pastelería (o carnicería o tienda de ropa o empresa que ud desee). Evite usar módulos como numpy, pandas o cualquier otro.

### **Rubrica**:

1. Generación de la clase que funcione correctamente con al menos 2 métodos y 2 atributos. **30 pts**.
2. Comentarios y  documentación que sirva para quien deba usar la clase. **5 pts**.
3. Pertinencia de la clase en el ámbito, ¿Por qué será útil esta herramienta y cómo ayudará a mejorar el negocio? esta será entregada en una celda de texto. **10 pts**.
4. ¿Cree que se pueda construir una clase hija que ayude al proceso? Si sí constrúyala, sino, argumente por qué en una célda de código. **5 pts**.

In [31]:
class Pedido:
    """
    Clase que permite tomar un pedido, agregar un producto y realizar el calculo del total de pedido

    argumentos:
    id_pedido (int): Codigo del pedido
    cliente (string): Nombre del cliente
    total (int): Total del pedido
    """

    total_pedidos = 0  # Variable inicializada en cero para contar el número de pedidos
    def __init__(self, id_pedido, cliente, total):
        self.id_pedido = id_pedido
        self.cliente = cliente
        self.total = total
        self.productos = []
        Pedido.total_pedidos += 1

    def agregar_producto(self, producto, cantidad):
        """
        Metodo que permite agregar un producto al pedido

        argumentos:
        producto: Objeto de la clase Producto
        cantidad: Cantidad del producto a agregar al pedido
        """

        self.productos.append((producto, cantidad))

    def calcular_total_pedido(self):
        """
        Metodo que permite calcular el total del pedido y el costo de los productos agregados

        Return
        - total_pedido: Total productos finales
        - total_por_producto: Total por producto
        """

        total_pedido = self.total
        total_por_producto = {}  # Diccionario para almacenar el total por producto
        for producto, cantidad in self.productos:
            total_producto = producto.precio * cantidad
            total_pedido += total_producto
            total_por_producto[producto.nombre] = total_producto  # Agregar al diccionario
        return total_pedido, total_por_producto

class Producto:
  """
  Clase que representa un producto, recibe el nombre del producto y su precio

  """
  def __init__(self,nombre, precio):
    self.nombre = nombre
    self.precio = precio


class PedidoPasteleria(Pedido):

  """
  Clase hija PedidoPasteleria que recibe de la clase Padre Pedido, representa un pedido especifico de la pasteleria

  Argumentos:
  idpedido: Identificador del pedido
  cliente: Nombre del cliente
  Total: Total inicial del pedido
  """
  total_pedidos_pasteleria = 0
  def __init__(self, id_pedido, cliente, total):
        super().__init__(id_pedido, cliente, total)
        PedidoPasteleria.total_pedidos_pasteleria += 1


# Listado de productos
producto1 = Producto("pan", 2000)
producto2 = Producto("Torta", 1000)

# Pedidos realizados a las pasteleria
pedido1 = PedidoPasteleria(1, "Sara", 0)
pedido1.agregar_producto(producto1, 2)

# Obtiene el valor total por producto y en general del pedido
total_pedido, total_por_producto = pedido1.calcular_total_pedido()
print("Total por producto:", total_por_producto)
print("Total Pedido:", total_pedido)


Total por producto: {'pan': 4000}
Total Pedido: 4000


3. Pertinencia de la clase en el ámbito, ¿Por qué será útil esta herramienta y cómo ayudará a mejorar el negocio? esta será entregada en una celda de texto.
R//
Es útil porque permite calcular el total de pedidos y por producto. La clase `Pedido` al tener funcionalidades generales, permite que otros negocios las reutilicen y las adapten a la medida o a las necesidades propias del negocio. En este caso, en el contexto de un pedido a una Pasteleria.

La clase hija en este caso es: `PedidoPasteleria`

## **Ejercicio 2** (50 pts)

Realice los siguientes ejercicios con numpy

1. Resolver el siguiente sistema de ecuaciones. **16 pts**

$$
2x + 3y - z + 4w + 5v = 15
$$

$$
x - 2y + 4z - 3w + v = 6
$$

$$
3x + 2y - 3z + 5w - 2v = 11
$$

$$
4x + y - 2z + 3w + 2v = 8
$$

$$
x + y + z + w + v = 7
$$

2. Calcule el valor del número de Euler o constante de Napier $e = 2,71828$ como:

$$e = \sum_i ^{\infty} \frac{1}{n!}$$

  ¿Qué precisión en términos de el número de términos necesita para dar cuenta de los primeros 5 números de la coma decimal? **18 pts**

3. Ecuentre los auto valores de la matriz.  **16 pts**

$$
\begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}
$$



### Punto 3.1

In [35]:
import numpy as np

# Definimos los coeficientes del sistema de ecuaciones:
coeficientes = np.array([
    [2, 3, -1, 4, 5],
    [1, -2, 4, -3, 1],
    [3, 2, -3, 5, -2],
    [4, 1, -2, 3, 2],
    [1, 1, 1, 1, 1]
])

# Definimos los resultados de las ecuaciones
resultados = np.array([15, 6, 11, 8, 7])

# Para resolver el sistema de ecuaciones usamos el submódulo "linalg"
# de numpy que proporciona funcionalidades de álgebra lineal y la función "solve"
# que nos permite resolver el sistema de ecuaciones lineales

solucion = np.linalg.solve(coeficientes, resultados)

# Mostrar la solución
print("La solución del sistema de ecuaciones dado es:")
print("x =", solucion[0])
print("y =", solucion[1])
print("z =", solucion[2])
print("w =", solucion[3])
print("v =", solucion[4])

La solución del sistema de ecuaciones dado es:
x = -1.6774193548387097
y = -7.870967741935485
z = 5.129032258064516
w = 10.0
v = 1.4193548387096777


# Punto 3.2

In [32]:
import numpy as np

# Definimos la función vectorizada "np.vectorize" que nos permite vectorizar
#(recibir elementos de arreglos) de una función ordinaria de python como "np.math.factorial" que normalmente trabaja con escalares
# La función devolverá el factorial correspondiente para cada arreglo de números enteros
factorial_vectorizado = np.vectorize(np.math.factorial)

# Definimos la función para calcular el número de Euler
def calcular_e(aproximaciones):
    n = np.arange(aproximaciones)  # la función "arange" crea un arreglo de 0 a aproximaciones - 1 con un paso de 1
    factoriales = factorial_vectorizado(n)  # Calcular el factorial de cada número en n con el "n" y el "factorial_vectorizado" ya definidos
    terminos = 1 / factoriales  # Se calculan los términos de la serie
    return np.sum(terminos)  # se suman los términos para obtener una aproximación de e

# Calculamos una aproximación de e usando 10 términos de la serie
aproximacion_e = calcular_e(10)
print("Aproximación de e con 10 términos:", aproximacion_e)

Aproximación de e con 10 términos: 2.718281525573192


###Punto 3.3

In [37]:
#Defino la matriz con la que voy a trabajar
mat = np.array([[2, 1, 1], [4, 3, 2], [1, 1, 2]])
print(mat)

[[2 1 1]
 [4 3 2]
 [1 1 2]]


In [38]:
# para calcular los autovalores (valores lambda) de una matriz, usamos la funcion linalg.eigvals de numpy
autovalores = np.linalg.eigvals(mat)

print(f'Los autovalores de la matriz son:',autovalores)

Los autovalores de la matriz son: [5.44948974 0.55051026 1.        ]
